# autopull/Dockerfile.autopull
FROM python:3.11-alpine

# docker-cli + compose plugin + fallback docker-compose, git и bash
RUN apk add --no-cache docker-cli docker-cli-compose docker-compose git bash

WORKDIR /work

# ваш скрипт автопуллера
COPY autopull.py /usr/local/bin/autopull.py
RUN chmod +x /usr/local/bin/autopull.py

ENV AUTOPULL_COLOR=1 \
    AUTOPULL_VERBOSE=1

ENTRYPOINT ["/usr/local/bin/autopull.py"]
